### ISSUE TITLE
Time out error

### ISSUE THREAD

**Issue by jonasestevam** [StefanYohansson/fipe-extractor#3]
> node get-fipe.js
Resulta em:
(node:4130) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: connect ETIMEDOUT 186.202.11.83:80

**Comment by StefanYohansson** [comment]
Vou dar uma olhada, pode me informar a versão do node utilizada?

**Comment by jonasestevam** [comment]
Node 8.0.0

**Comment by jonasestevam** [comment]
Atualizei pro Node 8.11.1 
Agora dá esse erro:

(node:21779) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 186.202.11.83:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
(node:21779) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21779) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:21779) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 186.202.11.83:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
(node:21779) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by StefanYohansson** [comment]
Tentei agora com a versão do node da minha máquina (10.0.0) e deu tudo certo.

Vou instalar a sua versão e tentar novamente.

Cada log "Tabela Fipe exportada com sucesso." é referente a um tipo da tabela.

caminhoes.json
carros.json
motos.json

```
snotr@Envy:~/Works/fipe-extractor$ node get-fipe.js 
Tabela Fipe exportada com sucesso.
Tabela Fipe exportada com sucesso.
Tabela Fipe exportada com sucesso.
snotr@Envy:~/Works/fipe-extractor$ ls
bootstrap_db.sql  caminhoes.json  carros.json  extract-fipe.sh  get-fipe.js  import-fipe.pl  motos.json  node_modules  package.json  package-lock.json  readme.md
snotr@Envy:~/Works/fipe-extractor$ node --version
v10.0.0
```

**Comment by jonasestevam** [comment]
Putz, então o problema é aqui.
Eu já fiz de tudo, e sempre dá esses erros.
Atualizei pro Node 10.0.0, pro 10.1.0, tentei no Windows 10, desliguei firewall do modem e do sistema, testei o site com o cURL e não dá problema... enfim
o que você acha que pode ser? estou ficando sem opções </3

**Comment by StefanYohansson** [comment]
Então, eu tava desconfiando de proxy ou firewall, mas você falou que desligou.

Tenta fazer um script simples em node para fazer um request para o site. Eu rodei no meu servidor também e está rodando normalmente.

caso precise apenas dos json, coloquei esse comando `node get-fipe.js > /dev/null | date > VERSION | tar vzcf fipe.tar.gz motos.json carros.json caminhoes.json VERSION > /dev/null` para rodar em uma cron todo dia de meia noite e servi aqui:

https://sadfeelings.me/fipe/fipe.tar.gz

Você pode checar o arquivo VERSION para ver de quando é o arquivo e se está atualizado em relação ao do dia anterior

**Comment by jonasestevam** [comment]
Muito obrigado, cara. Só precisava do .json mesmo.
Vou continuar tentando fazer o script funcionar na minha máquina, qualquer resultado positivo te informo aqui.

**Comment by StefanYohansson** [comment]
Valeu.
Vou fechar aqui. Porém, se encontrar o motivo abre e comenta aqui para que saibamos a causa.
